# Generated by Django 3.1.1 on 2020-11-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='groupno',
        ),
        migrations.RemoveField(
            model_name='market',
            name='orderno',
        ),
    ]
