# Generated by Django 3.1.1 on 2020-11-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20201119_2016'),
        ('market', '0003_auto_20201119_2204'),
    ]

    operations = [
    ]
