# Generated by Django 3.1.1 on 2020-11-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20201130_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='image',
            field=models.ImageField(blank=True, default='frame.png', null=True, upload_to='images/'),
        ),
    ]
