# Generated by Django 3.1.1 on 2020-11-30 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_blodapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blodapp',
        ),
    ]
