# Generated by Django 3.1.1 on 2020-10-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
