# Generated by Django 3.1.1 on 2020-11-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201112_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='user.png', upload_to='profiles'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
