# Generated by Django 3.1.1 on 2020-10-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20201021_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='photo',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d'),
        ),
    ]
