# Generated by Django 3.1.1 on 2020-10-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20201022_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('미술', '미술'), ('공예', '공예'), ('운동', '운동'), ('음악/댄스', '음악/댄스'), ('악기', '악기'), ('요리', '요리'), ('홈카페', '홈카페'), ('영화감상', '영화감상'), ('독서', '독서'), ('기타', '기타')], default='', max_length=5),
        ),
    ]
