# Generated by Django 3.1.1 on 2020-10-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20201022_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='category',
        ),
    ]
