# Generated by Django 3.1.1 on 2020-10-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20201027_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='image',
        ),
    ]
