# Generated by Django 3.1.1 on 2020-10-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_writer',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='board',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_contents',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='contents',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='comment',
            name='reg_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
