# Generated by Django 3.1.1 on 2020-11-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_remove_comment_comment_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_textfield',
            field=models.TextField(null=True),
        ),
    ]
