# Generated by Django 3.1.1 on 2020-11-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_auto_20201109_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='comment_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_textfield',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='comment_user',
        ),
    ]
