# Generated by Django 3.1.1 on 2020-11-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_auto_20201109_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_textfield',
            field=models.TextField(default=''),
        ),
    ]
