# Generated by Django 3.1.1 on 2020-11-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_auto_20201111_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_textfield',
            field=models.TextField(blank=True),
        ),
    ]
