# Generated by Django 3.1.1 on 2020-11-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0031_auto_20201112_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
