# Generated by Django 3.1.1 on 2020-11-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0033_auto_20201112_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
